apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: .dkr.ecr..amazonaws.com/how_about_there/server
  newName: .dkr.ecr..amazonaws.com/how_about_there/server
  newTag: abcdefg
resources:
- ../../base
patchesStrategicMerge:
- HAT-backEnd-deployment-patch.yaml
- hat-spring-backend-service-patch.yaml
