apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
images:
- name: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/how_about_there/server
  newName: 590184073129.dkr.ecr.ap-northeast-2.amazonaws.com/how_about_there/server
  newTag: 7eebd070
resources:
- ../../base
patchesStrategicMerge:
- HAT-backEnd-deployment-patch.yaml
- hat-spring-backend-service-patch.yaml
