---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-howAboutThere 
  region: ${AWS_REGION}
  version: "1.31"

vpc:
  cidr: "10.0.0.0/16" 
  nat:
    gateway: HighlyAvailable

managedNodeGroups:
  - name: node-group 
    instanceType: m5.large 
    desiredCapacity: 3 
    volumeSize: 20  
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true 
        albIngress: true  
        cloudWatch: true 
        autoScaler: true 
        ebs: true 

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

iam:
  withOIDC: true
