apiVersion: v1
kind: Service
metadata:
  name: hat-spring-backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
  labels:
    env: prod
spec:
  selector:
    app: hat-spring-backend
