apiVersion: apps/v1
kind: Deployment
metadata:
  name: hat-spring-backend
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: hat-spring-backend
  template:
    metadata:
      labels:
        app: hat-spring-backend
