apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/how_about_there/server
  newName: ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/how_about_there/server
  newTag: abcdefg
resources:
- ../base
patches:
- path: HAT-backend-deployment-patch.yaml
- path: hat-spring-backend-service-patch.yaml


